services:
  image-resizer-app:
    restart: unless-stopped
    container_name: image-resizer-app
    build: .
    env_file:
      - .env
    command: node src/index.js
networks:
  default:
    external: true
    name: shared-tunnel
